# Netlify configuration file for a Next.js project.
# This file ensures that all Next.js features, including the App Router,
# Server Actions, and API routes, are handled correctly by Netlify's build and hosting platform.

[build]
  # The command to build your Next.js application.
  command = "npm run build"

  # The directory where Next.js outputs the built site.
  # This is the standard output directory for Next.js.
  publish = ".next"

[build.environment]
  # Enable Next.js private worker for better performance
  NEXT_PRIVATE_WORKER_ENABLED = "true"
  # Set Node.js version for compatibility
  NODE_VERSION = "18"
  # Enable Next.js telemetry (optional)
  NEXT_TELEMETRY_DISABLED = "1"

# Redirects for Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[plugins]]
  # This is the essential plugin for deploying Next.js on Netlify.
  # It automatically configures redirects, rewrites, and other settings
  # to make all Next.js features work seamlessly.
  package = "@netlify/plugin-nextjs"
